
project_id = "suhttfxcurgurshlkcpz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000", 
  "https://go-travel-connect.vercel.app", 
  "https://bc24aefb-3820-4bdb-bbd4-aa7d5ea01cf8.lovableproject.com",
  "https://bc24aefb-3820-4bdb-bbd4-aa7d5ea01cf8.lovableproject.com/",
  "http://localhost:3000/",
  "https://go-travel-connect.vercel.app/",
  "https://*.lovableproject.com",
  "https://*.vercel.app"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[db]
port = 54323

[functions.google-places]
verify_jwt = false

[functions.google-places-enhanced]
verify_jwt = false

[storage]
enabled = true
port = 54324
image_transformation = {
  enabled = true
}
