
project_id = "suhttfxcurgurshlkcpz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "https://go-travel-connect.vercel.app"
additional_redirect_urls = ["http://localhost:3000", "https://go-travel-connect.vercel.app"]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[db]
port = 54323

[functions.google-places]
verify_jwt = false

[storage]
enabled = true
port = 54324
image_transformation = {
  enabled = true
}
