
project_id = "suhttfxcurgurshlkcpz"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[auth]
enabled = true
port = 54322
site_url = "http://localhost:3000"
additional_redirect_urls = [
  "http://localhost:3000", 
  "https://go-travel-connect.vercel.app", 
  "https://bc24aefb-3820-4bdb-bbd4-aa7d5ea01cf8.lovableproject.com",
  "https://bc24aefb-3820-4bdb-bbd4-aa7d5ea01cf8.lovableproject.com/",
  "http://localhost:3000/",
  "https://go-travel-connect.vercel.app/",
  "https://*.lovableproject.com",
  "https://*.vercel.app"
]
jwt_expiry = 3600
enable_signup = true
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = true

# Custom auth hooks
[auth.hook.custom_access_token]
enabled = false
uri = ""

[auth.hook.send_email]
enabled = true
uri = "https://suhttfxcurgurshlkcpz.supabase.co/functions/v1/auth-emails"

[auth.password]
min_length = 8
enable_password_strength = true
enable_leaked_password_protection = true

[auth.external.google]
enabled = true
skip_nonce_check = false

[db]
port = 54323

[functions.google-places]
verify_jwt = true

[functions.google-places-enhanced]
verify_jwt = true

[functions.send-trip-invitation]
verify_jwt = true

[functions.accept-trip-invitation]
verify_jwt = true

[functions.send-invitation-email]
verify_jwt = true

[functions.auth-emails]
verify_jwt = false

[functions.encrypt-document]
verify_jwt = true

[functions.decrypt-document]
verify_jwt = true

[functions.delete-document]
verify_jwt = true

[functions.list-documents]
verify_jwt = true

[storage]
enabled = true
port = 54324
image_transformation = {
  enabled = true
}
