export const places = [
  {
    id: "santorini-sunset-point",
    name: "Santorini Sunset Point",
    location: "Santorini, Greece",
    rating: 4.9,
    image: "🌅",
    category: "Tourist Attractions",
    description:
      "One of the world's most photographed sunsets with breathtaking views over the Aegean Sea.",
    hours: "Open 24/7",
    website: "www.santorini-tourism.com",
    phone: "+30 22860 22722",
    lat: 36.3932,
    lng: 25.4615,
  },
  {
    id: "kyoto-bamboo-grove",
    name: "Kyoto Bamboo Grove",
    location: "Kyoto, Japan",
    rating: 4.8,
    image: "🎋",
    category: "Parks",
    description:
      "Walk through thousands of towering bamboo stalks creating a natural cathedral.",
    hours: "6:00 AM - 6:00 PM",
    website: "www.kyoto-bamboo.jp",
    phone: "+81 75-211-1215",
    lat: 35.017,
    lng: 135.6728,
  },
  {
    id: "machu-picchu",
    name: "Machu Picchu",
    location: "Cusco, Peru",
    rating: 4.9,
    image: "🏔️",
    category: "Landmark",
    description: "Ancient Incan citadel set high in the Andes Mountains.",
    hours: "6:00 AM - 5:30 PM",
    website: "www.machupicchu.gob.pe",
    phone: "+51 84 211030",
    lat: -13.1631,
    lng: -72.545,
  },
  {
    id: "bondi-beach",
    name: "Bondi Beach",
    location: "Sydney, Australia",
    rating: 4.7,
    image: "🏖️",
    category: "Beaches",
    description:
      "Famous beach with golden sand and excellent surfing conditions.",
    hours: "24/7",
    website: "www.bondibeach.com",
    phone: "+61 2 9130 3000",
    lat: -33.8915,
    lng: 151.2767,
  },
  {
    id: "cafe-central-vienna",
    name: "Café Central",
    location: "Vienna, Austria",
    rating: 4.7,
    image: "☕",
    category: "Cafes",
    description: "Historic Viennese coffeehouse with traditional atmosphere.",
    hours: "7:30 AM - 10:00 PM",
    website: "www.cafecentral.wien",
    phone: "+43 1 533 37 64",
    lat: 48.2108,
    lng: 16.366,
  },
  {
    id: "grand-palace-bangkok",
    name: "Grand Palace",
    location: "Bangkok, Thailand",
    rating: 4.6,
    image: "🏰",
    category: "Tourist Attractions",
    description:
      "Ornate royal complex showcasing traditional Thai architecture.",
    hours: "8:30 AM - 3:30 PM",
    website: "www.grandpalacebangkok.com",
    phone: "+66 2 623 5500",
    lat: 13.75,
    lng: 100.4913,
  },
  {
    id: "central-park-nyc",
    name: "Central Park",
    location: "New York, USA",
    rating: 4.8,
    image: "🌳",
    category: "Parks",
    description: "Iconic urban park in the heart of Manhattan.",
    hours: "6:00 AM - 1:00 AM",
    website: "www.centralparknyc.org",
    phone: "+1 212-310-6600",
    lat: 40.7829,
    lng: -73.9654,
  },
  {
    id: "lake-bled",
    name: "Lake Bled",
    location: "Bled, Slovenia",
    rating: 4.8,
    image: "🏞️",
    category: "Lakes",
    description: "Picturesque alpine lake with a church on an island.",
    hours: "Open 24/7",
    website: "www.bled.si",
    phone: "+386 4 578 05 00",
    lat: 46.3683,
    lng: 14.1118,
  },
  {
    id: "louvre-museum",
    name: "Louvre Museum",
    location: "Paris, France",
    rating: 4.7,
    image: "🎨",
    category: "Museums",
    description: "World's largest art museum and historic monument.",
    hours: "9:00 AM - 6:00 PM",
    website: "www.louvre.fr",
    phone: "+33 1 40 20 50 50",
    lat: 48.8606,
    lng: 2.3376,
  },
  {
    id: "sydney-opera-house",
    name: "Sydney Opera House",
    location: "Sydney, Australia",
    rating: 4.9,
    image: "🎭",
    category: "Theatres",
    description: "Iconic performing arts venue with distinctive architecture.",
    hours: "Various show times",
    website: "www.sydneyoperahouse.com",
    phone: "+61 2 9250 7111",
    lat: -33.8568,
    lng: 151.2153,
  },
  {
    id: "ibiza-nightclub",
    name: "Pacha Ibiza",
    location: "Ibiza, Spain",
    rating: 4.5,
    image: "🎵",
    category: "Night Life",
    description: "World-famous nightclub with top international DJs.",
    hours: "11:00 PM - 6:00 AM",
    website: "www.pacha.com",
    phone: "+34 971 31 36 12",
    lat: 38.9072,
    lng: 1.4208,
  },
  {
    id: "disneyland-paris",
    name: "Disneyland Paris",
    location: "Paris, France",
    rating: 4.6,
    image: "🎠",
    category: "For Kids",
    description: "Magical theme park perfect for families and children.",
    hours: "10:00 AM - 10:00 PM",
    website: "www.disneylandparis.com",
    phone: "+33 1 60 30 60 53",
    lat: 48.8723,
    lng: 2.7756,
  },
  {
    id: "madison-square-garden",
    name: "Madison Square Garden",
    location: "New York, USA",
    rating: 4.4,
    image: "🎤",
    category: "Next Concerts",
    description: "Iconic venue hosting major concerts and sporting events.",
    hours: "Event dependent",
    website: "www.msg.com",
    phone: "+1 212-465-6741",
    lat: 40.7505,
    lng: -73.9934,
  },
  // Additional Landmarks
  {
    id: "statue-of-liberty",
    name: "Statue of Liberty",
    location: "New York, USA",
    rating: 4.8,
    image: "🗽",
    category: "Landmark",
    description: "Iconic symbol of freedom and democracy.",
    hours: "9:00 AM - 5:00 PM",
    website: "www.nps.gov/stli",
    phone: "+1 212-363-3200",
    lat: 40.6892,
    lng: -74.0445,
  },
  {
    id: "eiffel-tower",
    name: "Eiffel Tower",
    location: "Paris, France",
    rating: 4.9,
    image: "🗼",
    category: "Landmark",
    description: "Iconic iron lattice tower and symbol of France.",
    hours: "9:30 AM - 11:45 PM",
    website: "www.toureiffel.paris",
    phone: "+33 8 92 70 12 39",
    lat: 48.8584,
    lng: 2.2945,
  },
  {
    id: "taj-mahal",
    name: "Taj Mahal",
    location: "Agra, India",
    rating: 4.8,
    image: "🕌",
    category: "Landmark",
    description:
      "Stunning white marble mausoleum and UNESCO World Heritage site.",
    hours: "6:00 AM - 6:30 PM",
    website: "www.tajmahal.gov.in",
    phone: "+91 562 222 6431",
    lat: 27.1751,
    lng: 78.0421,
  },
  // Additional Beaches
  {
    id: "copacabana-beach",
    name: "Copacabana Beach",
    location: "Rio de Janeiro, Brazil",
    rating: 4.6,
    image: "🏖️",
    category: "Beaches",
    description: "Famous beach with vibrant nightlife and beach culture.",
    hours: "24/7",
    website: "www.copacabana.com.br",
    phone: "+55 21 2547-7522",
    lat: -22.9711,
    lng: -43.1822,
  },
  {
    id: "maya-bay",
    name: "Maya Bay",
    location: "Phi Phi Islands, Thailand",
    rating: 4.5,
    image: "🏝️",
    category: "Beaches",
    description: "Pristine beach surrounded by dramatic limestone cliffs.",
    hours: "10:00 AM - 4:00 PM",
    website: "www.phiphi.phuket.com",
    phone: "+66 75 612 188",
    lat: 7.6769,
    lng: 98.7681,
  },
  {
    id: "waikiki-beach",
    name: "Waikiki Beach",
    location: "Honolulu, Hawaii",
    rating: 4.7,
    image: "🌺",
    category: "Beaches",
    description: "Iconic Hawaiian beach perfect for surfing and relaxation.",
    hours: "24/7",
    website: "www.gohawaii.com/waikiki",
    phone: "+1 808-923-1311",
    lat: 21.2743,
    lng: -157.815,
  },
  // Additional Lakes
  {
    id: "lake-tahoe",
    name: "Lake Tahoe",
    location: "California/Nevada, USA",
    rating: 4.8,
    image: "🏔️",
    category: "Lakes",
    description: "Crystal clear alpine lake surrounded by mountains.",
    hours: "Open 24/7",
    website: "www.tahoesouth.com",
    phone: "+1 530-541-5255",
    lat: 39.0968,
    lng: -120.0324,
  },
  {
    id: "lake-como",
    name: "Lake Como",
    location: "Lombardy, Italy",
    rating: 4.9,
    image: "🛥️",
    category: "Lakes",
    description: "Stunning Italian lake surrounded by villas and mountains.",
    hours: "Open 24/7",
    website: "www.lakecomo.it",
    phone: "+39 031 269 712",
    lat: 45.9931,
    lng: 9.2611,
  },
  {
    id: "crater-lake",
    name: "Crater Lake",
    location: "Oregon, USA",
    rating: 4.7,
    image: "🌋",
    category: "Lakes",
    description: "Deep blue lake formed in a volcanic crater.",
    hours: "Open 24/7",
    website: "www.nps.gov/crla",
    phone: "+1 541-594-3000",
    lat: 42.8684,
    lng: -122.1685,
  },
  // Additional Concerts
  {
    id: "red-rocks-amphitheatre",
    name: "Red Rocks Amphitheatre",
    location: "Denver, USA",
    rating: 4.9,
    image: "🎸",
    category: "Next Concerts",
    description: "Natural amphitheatre with incredible acoustics.",
    hours: "Event dependent",
    website: "www.redrocksonline.com",
    phone: "+1 720-865-2494",
    lat: 39.6654,
    lng: -105.2057,
  },
  {
    id: "royal-albert-hall",
    name: "Royal Albert Hall",
    location: "London, UK",
    rating: 4.8,
    image: "🎼",
    category: "Next Concerts",
    description: "Historic concert hall hosting world-class performances.",
    hours: "Event dependent",
    website: "www.royalalberthall.com",
    phone: "+44 20 7589 8212",
    lat: 51.5009,
    lng: -0.1773,
  },
  {
    id: "sydney-opera-house-concerts",
    name: "Sydney Opera House Concerts",
    location: "Sydney, Australia",
    rating: 4.9,
    image: "🎵",
    category: "Next Concerts",
    description: "World-renowned venue for opera and concerts.",
    hours: "Event dependent",
    website: "www.sydneyoperahouse.com",
    phone: "+61 2 9250 7111",
    lat: -33.8568,
    lng: 151.2153,
  },
  // Additional Night Life
  {
    id: "berghain-berlin",
    name: "Berghain",
    location: "Berlin, Germany",
    rating: 4.6,
    image: "🌃",
    category: "Night Life",
    description: "Legendary techno club in a former power plant.",
    hours: "Saturday 11:59 PM - Monday 6:00 AM",
    website: "www.berghain.de",
    phone: "+49 30 2936 0210",
    lat: 52.5108,
    lng: 13.4429,
  },
  {
    id: "fabric-london",
    name: "Fabric",
    location: "London, UK",
    rating: 4.5,
    image: "🎶",
    category: "Night Life",
    description: "Iconic underground club with cutting-edge sound system.",
    hours: "Friday 11:00 PM - Saturday 7:00 AM",
    website: "www.fabriclondon.com",
    phone: "+44 20 7336 8898",
    lat: 51.52,
    lng: -0.1025,
  },
  {
    id: "omnia-las-vegas",
    name: "Omnia Nightclub",
    location: "Las Vegas, USA",
    rating: 4.4,
    image: "🎰",
    category: "Night Life",
    description: "Multi-level nightclub with world-class DJs.",
    hours: "Thursday - Sunday 10:30 PM - 4:00 AM",
    website: "www.omnianightclub.com",
    phone: "+1 702-785-6200",
    lat: 36.1147,
    lng: -115.1728,
  },
  // Additional Theatres
  {
    id: "broadway-theatre",
    name: "Broadway Theatre District",
    location: "New York, USA",
    rating: 4.8,
    image: "🎭",
    category: "Theatres",
    description: "World-famous theatre district with top musicals and plays.",
    hours: "Various show times",
    website: "www.broadway.com",
    phone: "+1 212-239-6200",
    lat: 40.759,
    lng: -73.9845,
  },
  {
    id: "west-end-london",
    name: "West End Theatres",
    location: "London, UK",
    rating: 4.7,
    image: "🎪",
    category: "Theatres",
    description: "London's premier theatre district with world-class shows.",
    hours: "Various show times",
    website: "www.officiallondontheatre.com",
    phone: "+44 20 7557 6700",
    lat: 51.5125,
    lng: -0.1308,
  },
  {
    id: "la-scala-milan",
    name: "La Scala",
    location: "Milan, Italy",
    rating: 4.9,
    image: "🎼",
    category: "Theatres",
    description: "World's most famous opera house.",
    hours: "Various show times",
    website: "www.teatroallascala.org",
    phone: "+39 02 88791",
    lat: 45.4674,
    lng: 9.1898,
  },
  // Additional For Kids
  {
    id: "universal-studios",
    name: "Universal Studios",
    location: "Orlando, USA",
    rating: 4.7,
    image: "🎢",
    category: "For Kids",
    description: "Exciting theme park with movie-themed attractions.",
    hours: "9:00 AM - 9:00 PM",
    website: "www.universalorlando.com",
    phone: "+1 407-363-8000",
    lat: 28.4754,
    lng: -81.4694,
  },
  {
    id: "legoland-denmark",
    name: "Legoland Billund",
    location: "Billund, Denmark",
    rating: 4.6,
    image: "🧱",
    category: "For Kids",
    description: "Original Legoland with amazing brick creations.",
    hours: "10:00 AM - 6:00 PM",
    website: "www.legoland.dk",
    phone: "+45 75 33 13 33",
    lat: 55.7367,
    lng: 9.1283,
  },
  {
    id: "tokyo-disneyland",
    name: "Tokyo Disneyland",
    location: "Tokyo, Japan",
    rating: 4.8,
    image: "🎪",
    category: "For Kids",
    description: "Magical Disney experience with unique Japanese touches.",
    hours: "8:00 AM - 10:00 PM",
    website: "www.tokyodisneyresort.jp",
    phone: "+81 45-330-5211",
    lat: 35.6329,
    lng: 139.8804,
  },
  // Additional Parks
  {
    id: "yellowstone-national-park",
    name: "Yellowstone National Park",
    location: "Wyoming, USA",
    rating: 4.9,
    image: "🌋",
    category: "Parks",
    description: "America's first national park with geysers and wildlife.",
    hours: "24/7",
    website: "www.nps.gov/yell",
    phone: "+1 307-344-7381",
    lat: 44.428,
    lng: -110.5885,
  },
  {
    id: "banff-national-park",
    name: "Banff National Park",
    location: "Alberta, Canada",
    rating: 4.8,
    image: "🏔️",
    category: "Parks",
    description: "Stunning mountain park with turquoise lakes.",
    hours: "24/7",
    website: "www.pc.gc.ca/banff",
    phone: "+1 403-762-1550",
    lat: 51.4968,
    lng: -115.9281,
  },
  // Additional Cafes
  {
    id: "blue-bottle-coffee",
    name: "Blue Bottle Coffee",
    location: "San Francisco, USA",
    rating: 4.5,
    image: "☕",
    category: "Cafes",
    description: "Artisanal coffee roasters with minimalist aesthetic.",
    hours: "6:00 AM - 7:00 PM",
    website: "www.bluebottlecoffee.com",
    phone: "+1 510-653-3394",
    lat: 37.7749,
    lng: -122.4194,
  },
  {
    id: "stumptown-coffee",
    name: "Stumptown Coffee",
    location: "Portland, USA",
    rating: 4.6,
    image: "☕",
    category: "Cafes",
    description: "Pioneer of third-wave coffee culture.",
    hours: "6:00 AM - 8:00 PM",
    website: "www.stumptowncoffee.com",
    phone: "+1 503-295-6144",
    lat: 45.5152,
    lng: -122.6784,
  },
  {
    id: "cafe-tortoni",
    name: "Café Tortoni",
    location: "Buenos Aires, Argentina",
    rating: 4.4,
    image: "☕",
    category: "Cafes",
    description: "Historic café with traditional Argentine atmosphere.",
    hours: "8:00 AM - 2:00 AM",
    website: "www.cafetortoni.com.ar",
    phone: "+54 11 4342-4328",
    lat: -34.6118,
    lng: -58.396,
  },
  // Additional Museums
  {
    id: "metropolitan-museum",
    name: "Metropolitan Museum",
    location: "New York, USA",
    rating: 4.8,
    image: "🏛️",
    category: "Museums",
    description:
      "One of the world's largest and most comprehensive art museums.",
    hours: "10:00 AM - 5:00 PM",
    website: "www.metmuseum.org",
    phone: "+1 212-535-7710",
    lat: 40.7794,
    lng: -73.9632,
  },
  {
    id: "british-museum",
    name: "British Museum",
    location: "London, UK",
    rating: 4.7,
    image: "🏺",
    category: "Museums",
    description: "World-famous museum with artifacts from around the globe.",
    hours: "10:00 AM - 5:00 PM",
    website: "www.britishmuseum.org",
    phone: "+44 20 7323 8299",
    lat: 51.5194,
    lng: -0.127,
  },
  {
    id: "prado-museum",
    name: "Prado Museum",
    location: "Madrid, Spain",
    rating: 4.8,
    image: "🎨",
    category: "Museums",
    description:
      "Premier collection of European art from 12th to 20th centuries.",
    hours: "10:00 AM - 8:00 PM",
    website: "www.museodelprado.es",
    phone: "+34 91 330 2800",
    lat: 40.4138,
    lng: -3.6921,
  },
];

export const categories = [
  "All",
  "Tourist Attractions",
  "Parks",
  "Cafes",
  "Museums",
  "Landmark",
  "Beaches",
  "Lakes",
  "Next Concerts",
  "Night Life",
  "Theatres",
  "For Kids",
];
