
export const places = [
  {
    id: "santorini-sunset-point",
    name: "Santorini Sunset Point",
    location: "Santorini, Greece",
    rating: 4.9,
    image: "🌅",
    category: "Tourist Attractions",
    description: "One of the world's most photographed sunsets with breathtaking views over the Aegean Sea.",
    hours: "Open 24/7",
    website: "www.santorini-tourism.com",
    phone: "+30 22860 22722",
    lat: 36.3932,
    lng: 25.4615
  },
  {
    id: "kyoto-bamboo-grove",
    name: "Kyoto Bamboo Grove",
    location: "Kyoto, Japan",
    rating: 4.8,
    image: "🎋",
    category: "Parks",
    description: "Walk through thousands of towering bamboo stalks creating a natural cathedral.",
    hours: "6:00 AM - 6:00 PM",
    website: "www.kyoto-bamboo.jp",
    phone: "+81 75-211-1215",
    lat: 35.0170,
    lng: 135.6728
  },
  {
    id: "machu-picchu",
    name: "Machu Picchu",
    location: "Cusco, Peru",
    rating: 4.9,
    image: "🏔️",
    category: "Landmark",
    description: "Ancient Incan citadel set high in the Andes Mountains.",
    hours: "6:00 AM - 5:30 PM",
    website: "www.machupicchu.gob.pe",
    phone: "+51 84 211030",
    lat: -13.1631,
    lng: -72.5450
  },
  {
    id: "bondi-beach",
    name: "Bondi Beach",
    location: "Sydney, Australia",
    rating: 4.7,
    image: "🏖️",
    category: "Beaches",
    description: "Famous beach with golden sand and excellent surfing conditions.",
    hours: "24/7",
    website: "www.bondibeach.com",
    phone: "+61 2 9130 3000",
    lat: -33.8915,
    lng: 151.2767
  },
  {
    id: "cafe-central-vienna",
    name: "Café Central",
    location: "Vienna, Austria",
    rating: 4.7,
    image: "☕",
    category: "Cafes",
    description: "Historic Viennese coffeehouse with traditional atmosphere.",
    hours: "7:30 AM - 10:00 PM",
    website: "www.cafecentral.wien",
    phone: "+43 1 533 37 64",
    lat: 48.2108,
    lng: 16.3660
  },
  {
    id: "grand-palace-bangkok",
    name: "Grand Palace",
    location: "Bangkok, Thailand",
    rating: 4.6,
    image: "🏰",
    category: "Tourist Attractions",
    description: "Ornate royal complex showcasing traditional Thai architecture.",
    hours: "8:30 AM - 3:30 PM",
    website: "www.grandpalacebangkok.com",
    phone: "+66 2 623 5500",
    lat: 13.7500,
    lng: 100.4913
  },
  {
    id: "central-park-nyc",
    name: "Central Park",
    location: "New York, USA",
    rating: 4.8,
    image: "🌳",
    category: "Parks",
    description: "Iconic urban park in the heart of Manhattan.",
    hours: "6:00 AM - 1:00 AM",
    website: "www.centralparknyc.org",
    phone: "+1 212-310-6600",
    lat: 40.7829,
    lng: -73.9654
  },
  {
    id: "lake-bled",
    name: "Lake Bled",
    location: "Bled, Slovenia",
    rating: 4.8,
    image: "🏞️",
    category: "Lakes",
    description: "Picturesque alpine lake with a church on an island.",
    hours: "Open 24/7",
    website: "www.bled.si",
    phone: "+386 4 578 05 00",
    lat: 46.3683,
    lng: 14.1118
  },
  {
    id: "louvre-museum",
    name: "Louvre Museum",
    location: "Paris, France",
    rating: 4.7,
    image: "🎨",
    category: "Museums",
    description: "World's largest art museum and historic monument.",
    hours: "9:00 AM - 6:00 PM",
    website: "www.louvre.fr",
    phone: "+33 1 40 20 50 50",
    lat: 48.8606,
    lng: 2.3376
  },
  {
    id: "sydney-opera-house",
    name: "Sydney Opera House",
    location: "Sydney, Australia",
    rating: 4.9,
    image: "🎭",
    category: "Theatres",
    description: "Iconic performing arts venue with distinctive architecture.",
    hours: "Various show times",
    website: "www.sydneyoperahouse.com",
    phone: "+61 2 9250 7111",
    lat: -33.8568,
    lng: 151.2153
  },
  {
    id: "ibiza-nightclub",
    name: "Pacha Ibiza",
    location: "Ibiza, Spain",
    rating: 4.5,
    image: "🎵",
    category: "Night Life",
    description: "World-famous nightclub with top international DJs.",
    hours: "11:00 PM - 6:00 AM",
    website: "www.pacha.com",
    phone: "+34 971 31 36 12",
    lat: 38.9072,
    lng: 1.4208
  },
  {
    id: "disneyland-paris",
    name: "Disneyland Paris",
    location: "Paris, France",
    rating: 4.6,
    image: "🎠",
    category: "For Kids",
    description: "Magical theme park perfect for families and children.",
    hours: "10:00 AM - 10:00 PM",
    website: "www.disneylandparis.com",
    phone: "+33 1 60 30 60 53",
    lat: 48.8723,
    lng: 2.7756
  },
  {
    id: "madison-square-garden",
    name: "Madison Square Garden",
    location: "New York, USA",
    rating: 4.4,
    image: "🎤",
    category: "Next Concerts",
    description: "Iconic venue hosting major concerts and sporting events.",
    hours: "Event dependent",
    website: "www.msg.com",
    phone: "+1 212-465-6741",
    lat: 40.7505,
    lng: -73.9934
  }
];

export const categories = [
  "All",
  "Tourist Attractions",
  "Parks",
  "Cafes",
  "Museums",
  "Landmark",
  "Beaches",
  "Lakes",
  "Next Concerts",
  "Night Life",
  "Theatres",
  "For Kids"
];
