
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suhttfxcurgurshlkcpz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aHR0ZnhjdXJndXJzaGxrY3B6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMjc4MTAsImV4cCI6MjA2NTYwMzgxMH0.2DLJSoUaSQel60qSaql3x9vRpO7LVXg3mu1qWdXo39g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    detectSessionInUrl: true
  }
});
